
export default [
    {title:"企业首页",url:'/index',icon:'el-icon-menu',name:'index',
      component:'index',roles:['input','approve']},
    {
      title:'申请类别',
      url:'/approvalApply',
      icon:'el-icon-menu',
      name:'approvalApply',component:'approvalApply',roles:['input'],
      children:[
        {
            title:'办公审批',
            url:'/approvalApply/officeApply',
            icon:'el-icon-menu',
            name:'officeApply',
            component:'approvalApply/officeApply'
        },
        {
            title:'请假审批',
            url:'/approvalApply/leaveApply',
            icon:'el-icon-menu',
            name:'leaveApply',
            component:'approvalApply/leaveApply'
        },
        {
          title:'差旅审批',
          url:'/approvalApply/travelApply',
          icon:'el-icon-menu',
          name:'travelApply',
          component:'approvalApply/travelApply'
      },
      ]
    },
    {
      title:'申请管理',
      url:'/approvalManage',
      icon:'el-icon-menu',
      name:'approvalManage',component:'approvalManage',roles:['input'],
      children:[
        {
            title:'办公审批',
            url:'/approvalManage/officeManage',
            icon:'el-icon-menu',
            name:'officeManage',
            component:'approvalManage/officeManage'
        },
        {
            title:'请假审批',
            url:'/approvalManage/leaveManage',
            icon:'el-icon-menu',
            name:'leaveManage',
            component:'approvalManage/leaveManage'
        },
        {
          title:'差旅审批',
          url:'/approvalManage/travelManage',
          icon:'el-icon-menu',
          name:'travelManage',
          component:'approvalManage/travelManage'
        },
      ]
    },
    {
      title:'审批流程',
      url:'/approvalProcess',
      icon:'el-icon-menu',
      name:'approvalProcess',component:'approvalProcess',roles:['approve'],
      children:[
        {title:'一审',url:'/approvalProcess/firstInstance',icon:'el-icon-menu',permission:['one'],
          name:'firstInstance',component:'approvalProcess/firstInstance'},
        {title:'二审',url:'/approvalProcess/secondInstance',icon:'el-icon-menu',permission:['two'],
          name:'secondInstance',component:'approvalProcess/secondInstance'},
        {title:'终审',url:'/approvalProcess/lastInstance',icon:'el-icon-menu',permission:['end'],
          name:'lastInstance',component:'approvalProcess/lastInstance'}
      ]
    },
    {title:'档案管理',url:'/fileManage',icon:'el-icon-menu',name:'fileManage',
      component:'fileManage',roles:['input']},
    {
      title:'权限管理',
      url:'/powerManage',
      icon:'el-icon-menu',
      name:'powerManage',component:'powerManage',
      children:[
        {title:'创建员工与审批员',url:'/powerManage/createUser',icon:'el-icon-menu',name:'createUser',component:'powerManage/createUser'},
        {title:'员工与审批员列表',url:'/powerManage/userLists',icon:'el-icon-menu',name:'userLists',component:'powerManage/userLists'},
        {title:'审批员权限',url:'/powerManage/modifyPower',icon:'el-icon-menu',name:'modifyPower',component:'powerManage/modifyPower'}
      ]
    },
  ]

 